apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
type: Opaque
stringData:
  age.agekey: |
    # created by: age-keygen -o age.key
    # public key: age17kh7xgfslh7f6t4f84etr06e7tgm32qptqswsvk7lrng9wk4fv5s55yv2r
    AGE-SECRET-KEY-1ERWDG6F0L8FNPQYT9JK4MZSTXUGXLAQUH7JXR2JTR5F5QCYD90MQWE64DU
