apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"omega-monitor"},"name":"omega-monitor","namespace":"arc-omega"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"omega-monitor"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"omega-monitor"}},"spec":{"containers":[{"env":[{"name":"NATS_URL","valueFrom":{"secretKeyRef":{"key":"NATS_URL","name":"omega-nats-auth"}}},{"name":"NATS_SUBJECT","value":"omega.reason"},{"name":"NATS_QUEUE","value":"omega-workers"}],"image":"ghcr.io/silentsage432/omega-monitor:latest","imagePullPolicy":"Always","livenessProbe":{"exec":{"command":["python","-c","import urllib.request; urllib.request.urlopen('http://localhost:8080/health', timeout=5)"]},"failureThreshold":6,"initialDelaySeconds":20,"periodSeconds":20,"timeoutSeconds":5},"name":"monitor","ports":[{"containerPort":8080,"name":"http"}],"readinessProbe":{"exec":{"command":["python","-c","import urllib.request; urllib.request.urlopen('http://localhost:8080/health', timeout=5)"]},"failureThreshold":6,"initialDelaySeconds":10,"periodSeconds":10,"timeoutSeconds":5},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":true,"runAsGroup":10001,"runAsNonRoot":true,"runAsUser":10001},"volumeMounts":[{"mountPath":"/tmp","name":"tmp"}]}],"securityContext":{"seccompProfile":{"type":"RuntimeDefault"}},"volumes":[{"emptyDir":{},"name":"tmp"}]}}}}
  creationTimestamp: "2025-10-26T03:37:43Z"
  generation: 16
  labels:
    app: omega-monitor
  name: omega-monitor
  namespace: arc-omega
  resourceVersion: "5228320"
  uid: 71fc7d80-4c00-48ab-b12f-b9b55049e96b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: omega-monitor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-27T21:06:10-06:00"
      labels:
        app: omega-monitor
    spec:
      containers:
      - image: ghcr.io/silentsage432/omega-monitor:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - import urllib.request; urllib.request.urlopen('http://localhost:8080/health',
              timeout=5)
          failureThreshold: 6
          initialDelaySeconds: 20
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        name: monitor
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - import urllib.request; urllib.request.urlopen('http://localhost:8080/health',
              timeout=5)
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-26T03:47:18Z"
    lastUpdateTime: "2025-10-26T03:47:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-26T03:37:43Z"
    lastUpdateTime: "2025-10-28T03:11:43Z"
    message: ReplicaSet "omega-monitor-dc6f6cb67" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 16
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
