apiVersion: apps/v1
kind: Deployment
metadata:
  name: observer-api
  namespace: arc-zeta
spec:
  replicas: 1
  selector:
    matchLabels: { app: observer-api }
  template:
    metadata:
      labels: { app: observer-api }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile: { type: RuntimeDefault }
      containers:
      - name: api
        image: python:3.11-slim
        command: ["/bin/sh","-lc"]
        args:
          - |
            set -e
            python -m pip install --no-cache-dir fastapi uvicorn[standard] nats-py
            exec uvicorn app:app --host 0.0.0.0 --port 8080
        env:
        - name: NATS_URL
          value: "nats://nats.infra.svc.cluster.local:4222"
        - name: SUBJECTS
          value: "arc.>"
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: app
          mountPath: /app
          readOnly: true
        readinessProbe:
          httpGet: { path: /health, port: http }
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /health, port: http }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests: { cpu: "60m", memory: "192Mi" }
          limits:   { cpu: "500m", memory: "512Mi" }
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false   # allow pip install
          capabilities: { drop: ["ALL"] }
      volumes:
      - name: app
        configMap:
          name: observer-api-code
          items:
          - key: app.py
            path: app.py
      nodeSelector: { kubernetes.io/os: linux }
      tolerations:
      - { key: "node-role.kubernetes.io/control-plane", operator: "Exists", effect: "NoSchedule" }
