apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # include your existing infra manifests here
  - ./nats.yaml
# Generate nats-auth here instead of committing raw Secret
secretGenerator:
  - name: nats-auth
    literals:
      - token=SAGE_SUPER_TOKEN
generatorOptions:
  disableNameSuffixHash: true
