apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Only list the resources we actually need Infra to manage
resources:
  - namespace.yaml
  - nats.yaml
  - kustomization-prod.yaml

# Force ONLY the 'prod' Flux Kustomization to live in flux-system
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: prod
    path: patches/prod-ks-namespace.yaml
