apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
resources:
  - namespace.yaml
  - nats-secret.yaml     # single source of the Secret
  - nats.yaml            # deploy/service/etc. (no Secret inside)
