apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
resources:
  - namespace.yaml
  - nats.yaml            # keep this if you actually have it; otherwise comment it out
  - nats-secret.yaml     # <-- the ONLY source of the Secret now
