apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
resources:
  - namespace.yaml
  - nats.yaml          # keep this only if it DOESN'T contain a nats-auth Secret
  - nats-secret.yaml   # <- the ONLY source of the Secret
