apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "5"
    creationTimestamp: "2025-10-05T12:15:34Z"
    generation: 5
    labels:
      kustomize.toolkit.fluxcd.io/name: infra
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: nats
    namespace: infra
    resourceVersion: "451432"
    uid: 2b995f35-e9e1-4fdd-bb75-554ff690c339
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: nats
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: nats
      spec:
        containers:
        - args:
          - -js
          - -p
          - "4222"
          - -m
          - "8222"
          - -sd
          - /data
          env:
          - name: NATS_TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: nats-auth
          image: nats:2.10
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /varz
              port: monitor
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: nats
          ports:
          - containerPort: 4222
            name: client
            protocol: TCP
          - containerPort: 8222
            name: monitor
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /varz
              port: monitor
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /data
            name: data
        dnsPolicy: ClusterFirst
        nodeSelector:
          kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 10001
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        volumes:
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: data
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-10-05T12:30:57Z"
      lastUpdateTime: "2025-10-05T12:30:57Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-10-05T12:30:44Z"
      lastUpdateTime: "2025-10-05T12:38:11Z"
      message: ReplicaSet "nats-6c5d4bfcb5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 5
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-10-05T05:15:28Z"
    labels:
      kustomize.toolkit.fluxcd.io/name: infra
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: nats
    namespace: infra
    resourceVersion: "366284"
    uid: 4fd716e3-6a95-4e85-9461-318f9d6db0bd
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: client
      port: 4222
      protocol: TCP
      targetPort: 4222
    - name: monitor
      port: 8222
      protocol: TCP
      targetPort: 8222
    selector:
      app: nats
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  data:
    token: cGxlYXNlLWNoYW5nZS1tZS10by1hLWxvbmctcmFuZG9tLXN0cmluZw==
  kind: Secret
  metadata:
    creationTimestamp: "2025-10-05T05:15:28Z"
    labels:
      kustomize.toolkit.fluxcd.io/name: infra
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: nats-auth
    namespace: infra
    resourceVersion: "363057"
    uid: 57e642c8-6d6c-46df-b936-1247f2378641
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
