apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-static-config
  namespace: observability
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    clients:
      - url: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push
    positions:
      filename: /run/promtail/positions.yaml
    scrape_configs:
      - job_name: static-omega-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: omega-logs
              namespace: arc-omega
              app: omega-monitor
        pipeline_stages:
          - json:
              expressions:
                reason_code:
                note:
                received_at:
          - labels:
              reason_code:
