apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-ui
resources:
  - ../../../_base/app
  - service.yaml
namePrefix: ui-
commonLabels:
  app: ui
  rho2.identity: arc-ui
patches:
  - target: { kind: Deployment, name: APPNAME }
    patch: |-
      - op: replace
        path: /metadata/name
        value: sage-enterprise-ui
      - op: replace
        path: /spec/selector/matchLabels/app
        value: ui
      - op: replace
        path: /spec/template/metadata/labels/app
        value: ui
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: sage-enterprise-ui
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: silentsage432/sage-ui:prod-20251001
      - op: replace
        path: /spec/template/spec/containers/1/name
        value: ui-leaf
      - op: replace
        path: /spec/template/spec/volumes/0/configMap/name
        value: ui-leaf-config
  - target: { kind: ConfigMap, name: APPNAME-leaf-config }
    patch: |-
      - op: replace
        path: /metadata/name
        value: ui-leaf-config
      - op: replace
        path: /data/nats.conf
        value: |
          port: 4222
          server_name: "ui-leaf"
          leafnodes { remotes = [ { url: "nats://${NATS_USER}:${NATS_PASS}@${CHI_HOST}:${CHI_LEAF_PORT}" } ] }
  - target: { kind: CiliumNetworkPolicy, name: APPNAME-egress }
    patch: |-
      - op: replace
        path: /metadata/name
        value: ui-egress
      - op: replace
        path: /spec/endpointSelector/matchLabels/app
        value: ui
images:
  - name: REPLACE_APP_IMAGE
    newName: silentsage432/sage-ui
    newTag: prod-20251001
configMapGenerator: []
