apiVersion: v1
kind: Service
metadata:
  name: sage-enterprise-ui
  namespace: arc-ui
  labels:
    app: ui
spec:
  selector:
    app: ui
  ports:
    - { name: http, port: 8080, targetPort: 8080, protocol: TCP }
