apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    adminUser: admin
    adminPassword: change-me

    service:
      type: ClusterIP
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "grafana"
        tailscale.com/tags: "tag:k8s"

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            # kube-prometheus-stack's Prometheus service name:
            url: http://kube-prom-kube-prometheus-prometheus.observability.svc.cluster.local:9090
          - name: Loki
            type: loki
            access: proxy
            url: http://loki-gateway.observability.svc.cluster.local

    sidecar:
      dashboards:
        enabled: true
        folder: /var/lib/grafana/dashboards/auto
        label: grafana_dashboard
