apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  interval: 10m
  timeout: 10m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 8.5.12
  values:
    adminUser: admin
    adminPassword: "change-me"
    service:
      type: ClusterIP
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "grafana"
        tailscale.com/tags: "tag:k8s"
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://kube-prom-prometheus.observability.svc.cluster.local
            access: proxy
            isDefault: false
          - name: Loki
            type: loki
            url: http://loki-gateway.observability.svc.cluster.local
            access: proxy
            isDefault: true
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        folder: /var/lib/grafana/dashboards/auto
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile: {type: RuntimeDefault}
    containerSecurityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities: {drop: ["ALL"]}
