# clusters/prod/observability/kube-prom-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prom
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
       operator: Exists
       effect: NoSchedule
    grafana:
      enabled: false
    alertmanager:
      alertmanagerSpec:
        retention: 120h
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
    prometheus:
      prometheusSpec:
        retention: 15d
        scrapeInterval: 30s
        evaluationInterval: 30s
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        service:
          type: ClusterIP
          annotations:
            tailscale.com/expose: "true"
            tailscale.com/hostname: "prometheus"
            tailscale.com/tags: "tag:k8s"
    kube-state-metrics:
      enabled: true
    nodeExporter:
      enabled: true
