apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      # leave version unset to get the chart's default/latest compatible
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    # *** SINGLE BINARY ONLY ***
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: boltdb-shipper
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
    singleBinary:
      persistence:
        enabled: true
        size: 20Gi
    gateway:
      enabled: true
      service:
        type: ClusterIP
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "loki"
        tailscale.com/tags: "tag:k8s"
