apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 10m
  timeout: 10m0s
  install: {remediation: {retries: 3}, disableWait: true}
  upgrade: {remediation: {retries: 3}, disableWait: true, force: true}
  test: {enable: false}
  chart:
    spec:
      chart: loki
      version: 5.43.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    deploymentMode: SingleBinary
    # Keep validators happy but DO NOT spin up extra agents/DS
    monitoring:
      selfMonitoring:
        enabled: false
      lokiCanary:
        enabled: false
      grafanaAgent:
        enabled: false
        installOperator: false
    canary:
      enabled: false
    loki:
      auth_enabled: false
      storageConfig:
        boltdb_shipper:
          active_index_directory: /tmp/loki/index
          cache_location: /tmp/loki/boltdb-cache
          shared_store: filesystem
        filesystem:
          directory: /tmp/loki/chunks
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: boltdb-shipper
            object_store: filesystem
            schema: v13
            index: {prefix: index_, period: 24h}
      commonConfig:
        replication_factor: 1
      analytics:
        reporting_enabled: false
      server:
        http_listen_port: 3100
        grpc_listen_port: 9095
    singleBinary:
      replicas: 1
      persistence:
        enabled: false # <-- ephemeral to avoid PVC/PSS drama
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
    gateway:
      enabled: true
      service: {type: ClusterIP}
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "loki"
        tailscale.com/tags: "tag:k8s"
    # Ensure distributed bits NEVER render
    read: {replicas: 0}
    write: {replicas: 0}
    backend: {replicas: 0}
    chunksCache: {enabled: false}
    # Security hardening so PSS won’t complain if labels change later
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile: {type: RuntimeDefault}
    containerSecurityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities: {drop: ["ALL"]}
    lokiCanary:
      enabled: false
    test:
      enabled: false
