apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      # Pin to a widely used stable to avoid validator drift; you can bump later
      version: 5.43.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      # The chart's validator expects storageConfig in many versions
      storageConfig:
        boltdb_shipper:
          active_index_directory: /var/loki/index
          cache_location: /var/loki/boltdb-cache
          shared_store: filesystem
        filesystem:
          directory: /var/loki/chunks
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: boltdb-shipper
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
    singleBinary:
      persistence:
        enabled: true
        size: 20Gi
        accessModes: ["ReadWriteOnce"]
        # storageClass: ""  # set if you have a named SC; else default
    gateway:
      enabled: true
      service:
        type: ClusterIP
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "loki"
        tailscale.com/tags: "tag:k8s"
