# clusters/prod/observability/loki-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: 6.x.x
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      server: { http_listen_port: 3100 }
      commonConfig: { replication_factor: 1 }
      storage: { type: filesystem }
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: boltdb-shipper
            object_store: filesystem
            schema: v13
            index: { prefix: index_, period: 24h }
    compactor: { retention_enabled: true }
    limits_config: { retention_period: 168h } # 7 days
    gateway:
      enabled: true
      service:
        type: ClusterIP
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "loki"
        tailscale.com/tags: "tag:k8s"