apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 10m
  timeout: 10m0s
  install:
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }
  # ⬇️ Do NOT run helm tests for this chart
  test:
    enable: false
  chart:
    spec:
      chart: loki
      version: 5.43.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    # *** SINGLE BINARY ONLY ***
    deploymentMode: SingleBinary

    # Belt & suspenders: make sure chart-level tests are off too
    test:
      enabled: false

    # Make absolutely sure distributed bits do NOT render
    read:     { replicas: 0 }
    write:    { replicas: 0 }
    backend:  { replicas: 0 }
    chunksCache: { enabled: false }
    monitoring:
      selfMonitoring:
        enabled: false
      lokiCanary:
        enabled: false
      grafanaAgent:
        enabled: false
    canary:
      enabled: false

    loki:
      auth_enabled: false
      storageConfig:
        boltdb_shipper:
          active_index_directory: /var/loki/index
          cache_location: /var/loki/boltdb-cache
          shared_store: filesystem
        filesystem:
          directory: /var/loki/chunks
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: boltdb-shipper
            object_store: filesystem
            schema: v13
            index: { prefix: index_, period: 24h }

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 20Gi
        accessModes: ["ReadWriteOnce"]

    gateway:
      enabled: true
      service: { type: ClusterIP }
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "loki"
        tailscale.com/tags: "tag:k8s"

    # PSS hardening
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile: { type: RuntimeDefault }
    containerSecurityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities: { drop: ["ALL"] }
