apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-node-exporter
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus-node-exporter
      version: 4.33.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    hostNetwork: true
    hostPID: true
    service:
      port: 9100
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prom
      interval: 30s
      scrapeTimeout: 10s
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
