apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: observability
spec:
  interval: 10m
  timeout: 10m0s
  install: {remediation: {retries: 3}}
  upgrade: {remediation: {retries: 3}}
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    config:
      clients:
        - url: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push
      snippets:
        pipelineStages:
          - cri: {}
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile: {type: RuntimeDefault}
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities: {drop: ["ALL"]}
  suspend: true
