# clusters/prod/observability/promtail-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: promtail
      version: 6.x.x
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    config:
      clients:
        - url: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push
      snippets:
        pipelineStages:
          - cri: {}
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
