apiVersion: apps/v1
kind: Deployment
metadata:
  name: omega-monitor
  namespace: arc-omega
  labels: { app: omega-monitor }
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
  selector:
    matchLabels: { app: omega-monitor }
  template:
    metadata:
      labels: { app: omega-monitor }
    spec:
      securityContext:
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: monitor
          image: ghcr.io/silentsage432/omega-monitor:latest
          imagePullPolicy: Always
          ports: [ { name: http, containerPort: 8080 } ]
          env:
            - { name: NATS_URL,     valueFrom: { secretKeyRef: { name: "omega-nats-auth", key: "NATS_URL" } } }
            - { name: NATS_SUBJECT, value: "omega.reason" }
            - { name: NATS_QUEUE,   value: "omega-workers" }
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          volumeMounts:
            - { name: tmp, mountPath: /tmp }
          readinessProbe:
            exec:
              command:
                - python
                - -c
                - "import urllib.request; urllib.request.urlopen('http://localhost:8080/health', timeout=5)"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - "import urllib.request; urllib.request.urlopen('http://localhost:8080/health', timeout=5)"
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
      volumes:
        - name: tmp
          emptyDir: {}