apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "28"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"omega-monitor"},"name":"omega-monitor","namespace":"arc-omega"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"omega-monitor"}},"template":{"metadata":{"labels":{"app":"omega-monitor"}},"spec":{"containers":[{"env":[{"name":"NATS_URL","value":"nats://chi-bus.arc-chi.svc.cluster.local:4222"},{"name":"REASON_CODES_PATH","value":"/etc/omega/reason-codes.json"},{"name":"OMEGA_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"ghcr.io/stefanprodan/podinfo:6.7.1","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":9898},"initialDelaySeconds":10,"periodSeconds":15,"timeoutSeconds":1},"name":"monitor","ports":[{"containerPort":9898,"name":"http"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/readyz","port":9898},"initialDelaySeconds":5,"periodSeconds":10,"timeoutSeconds":1},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":true,"runAsNonRoot":true},"volumeMounts":[{"mountPath":"/etc/omega","name":"reason-codes","readOnly":true}]}],"imagePullSecrets":[{"name":"ghcr-cred"}],"securityContext":{"seccompProfile":{"type":"RuntimeDefault"}},"serviceAccountName":"omega-monitor","volumes":[{"configMap":{"items":[{"key":"reason-codes.json","path":"reason-codes.json"}],"name":"omega-reason-codes"},"name":"reason-codes"}]}}}}
  creationTimestamp: "2025-10-25T20:03:36Z"
  generation: 56
  labels:
    app: omega-monitor
  name: omega-monitor
  namespace: arc-omega
  resourceVersion: "4802172"
  uid: 195d108e-c1bc-4e08-bf00-b0eec906fa7d
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: omega-monitor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-25T19:28:28-06:00"
      labels:
        app: omega-monitor
    spec:
      containers:
      - image: ghcr.io/silentsage432/omega-monitor:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - import urllib.request,sys;print(urllib.request.urlopen('http://127.0.0.1:8080/health',timeout=4).read().decode())
          failureThreshold: 6
          initialDelaySeconds: 20
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        name: monitor
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - import urllib.request,sys;print(urllib.request.urlopen('http://127.0.0.1:8080/health',timeout=4).read().decode())
          failureThreshold: 6
          initialDelaySeconds: 8
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: omega-monitor
      serviceAccountName: omega-monitor
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-26T01:27:13Z"
    lastUpdateTime: "2025-10-26T01:27:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-26T01:13:05Z"
    lastUpdateTime: "2025-10-26T01:28:46Z"
    message: ReplicaSet "omega-monitor-85c499684b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 56
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
