apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"omega-monitor","namespace":"arc-omega"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":9898}],"selector":{"app":"omega-monitor"}}}
  creationTimestamp: "2025-10-25T20:03:36Z"
  name: omega-monitor
  namespace: arc-omega
  resourceVersion: "4778636"
  uid: f7fa5f9b-5d2f-436c-93d3-38d7bf730532
spec:
  clusterIP: 10.99.50.7
  clusterIPs:
  - 10.99.50.7
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: omega-monitor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
