apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sage
  namespace: sage
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /sage
            pathType: Prefix
            backend:
              service:
                name: sage
                port:
                  number: 80
