apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: arcs
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true
  dependsOn:
    - name: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/arcs
