# clusters/prod/platform/tailscale/helmrepository.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tailscale
  namespace: flux-system
spec:
  url: https://pkgs.tailscale.com/helmcharts
  interval: 10m