apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale
resources:
  - ns.yaml
  - tailscale-helmrepo.yaml
  - tailscale-operator-helmrelease.yaml
  - proxyclass-default.yaml
