apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: 1.x.x
  install:
    crds: Create
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    disableWait: true
    remediation:
      retries: 3
  values:
    authKey:
       secretName: tailscale-auth
       secretKey: tskey-auth-k45iqkzWY911CNTRL-kUJBdutGwf9WVpYWZtgDf9Mzqnv4tGww
    # REQUIRED: OAuth (operator requires this)
    oauth:
      clientId: kE28RkVJpX11CNTRL       # looks like 'client:xxxxxxxx...'
      clientSecret: tskey-client-kE28RkVJpX11CNTRL-eMkU3ipTZGY2megicTn4GYKWM4rMfJkCB # the long secret you copied

    # Operator & proxy default tags
    operatorConfig:
      defaultTags: "tag:k8s-operator"
      logging: info
    proxyConfig:
      defaultProxyClass: default
      defaultTags: "tag:k8s"
