apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: 1.x.x
  values:
    # <-- put the fresh OAuth client from the Tailscale admin here -->
    oauth:
      clientId: "<YOUR_CLIENT_ID>"        # e.g. 3C3C8D3B... (not tskey-…)
      clientSecret: "<YOUR_CLIENT_SECRET>"# the long mixed-case secret

    # keep tags simple; operator earns k8s-operator and can assign 'k8s'
    operatorConfig:
      defaultTags: "tag:k8s-operator"
    proxyConfig:
      defaultProxyClass: default
      defaultTags: "tag:k8s"
