apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: 1.x.x
  values:
    oauth:
      existingSecret: operator-oauth
      clientIdKey: client_id
      clientSecretKey: client_secret

    operatorConfig:
      logging: info

    proxyConfig:
      defaultProxyClass: default
      defaultTags: "tag:k8s"
