apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: 1.x.x
  values:
    # Use an AUTH KEY (tskey-auth-...), not a client secret.
    authKey:
      secretName: tailscale-auth
      secretKey: TS_AUTHKEY

    operatorConfig:
      logging: info

    proxyConfig:
      defaultProxyClass: default
      # MUST be a string on 1.88.x charts
      defaultTags: "tag:k8s"
