apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: 1.x.x
  values:
    # ✅ Auth-key mode only
    authKey:
      secretName: tailscale-auth
      secretKey: TS_AUTHKEY

    # operator + proxy tags
    operatorConfig:
      defaultTags: "tag:k8s-operator"
    proxyConfig:
      defaultProxyClass: default
      defaultTags: "tag:k8s"
