apiVersion: v1
kind: ConfigMap
metadata:
  name: epsilon-nginx
  namespace: arc-epsilon
data:
  nginx.conf: |
    events {}
    http {
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;

      server {
        listen 8080;
        server_name _;
        root /usr/share/nginx/html;
        location / {
          try_files $uri /index.html;
        }
      }
    }
