apiVersion: v1
kind: ConfigMap
metadata:
  name: epsilon-nginx
  namespace: arc-epsilon
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8080;
        server_name _;
        root /usr/share/nginx/html;
        location / {
          try_files $uri /index.html;
        }
      }
    }
