apiVersion: apps/v1
kind: Deployment
metadata:
  name: epsilon-ui
  namespace: arc-epsilon
spec:
  replicas: 1
  selector: { matchLabels: { app: epsilon-ui } }
  template:
    metadata:
      labels: { app: epsilon-ui }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile: { type: RuntimeDefault }
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.27-alpine
        # Unprivileged image listens on 8080 by default
        ports: [{ name: http, containerPort: 8080 }]
        volumeMounts:
        - { name: site,  mountPath: /usr/share/nginx/html, readOnly: true }
        - { name: theme, mountPath: /usr/share/nginx/html/theme, readOnly: true }
        - { name: tmp,   mountPath: /tmp }  # writable temp for proxy cache etc
        resources:
          requests: { cpu: "20m", memory: "64Mi" }
          limits:   { cpu: "200m", memory: "128Mi" }
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        readinessProbe:
          httpGet: { path: /, port: http }
          initialDelaySeconds: 2
          periodSeconds: 5
      volumes:
      - name: site
        configMap:
          name: epsilon-ui
          items: [{ key: index.html, path: index.html }]
      - name: theme
        configMap:
          name: epsilon-theme
      - name: tmp
        emptyDir: {}
      nodeSelector: { kubernetes.io/os: linux }
      tolerations:
      - { key: "node-role.kubernetes.io/control-plane", operator: "Exists", effect: "NoSchedule" }
