apiVersion: apps/v1
kind: Deployment
metadata:
  name: epsilon-ui
  namespace: arc-epsilon
spec:
  replicas: 1
  selector: { matchLabels: { app: epsilon-ui } }
  template:
    metadata:
      labels: { app: epsilon-ui }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile: { type: RuntimeDefault }
      containers:
      - name: web
        image: nginx:1.27-alpine
        ports: [{ name: http, containerPort: 80 }]
        volumeMounts:
        - { name: site, mountPath: /usr/share/nginx/html, readOnly: true }
        resources:
          requests: { cpu: "20m", memory: "64Mi" }
          limits:   { cpu: "200m", memory: "128Mi" }
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
      volumes:
      - name: site
        configMap:
          name: epsilon-ui
          items: [{ key: index.html, path: index.html }]
      nodeSelector: { kubernetes.io/os: linux }
      tolerations:
      - { key: "node-role.kubernetes.io/control-plane", operator: "Exists", effect: "NoSchedule" }
