apiVersion: v1
kind: Namespace
metadata:
  name: tailscale-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-operator
  namespace: tailscale-operator
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale-operator
type: Opaque
stringData:
  authkey: "PLACEHOLDER_AUTHKEY"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-operator
  namespace: tailscale-operator
  labels:
    app: tailscale-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-operator
  template:
    metadata:
      labels:
        app: tailscale-operator
    spec:
      serviceAccountName: tailscale-operator
      containers:
      - name: operator
        image: tailscale/k8s-operator:v1.88.4
        imagePullPolicy: Always
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: authkey
        - name: TS_EXTRA_ARGS
          value: "--advertise-tags=tag:k8s-operator"
        - name: TS_USERSPACE
          value: "true"
        - name: TS_AUTH_ONCE
          value: "true"
        - name: TS_STATE_DIR
          value: "/var/lib/tailscale"
        volumeMounts:
        - name: tailscale-state
          mountPath: /var/lib/tailscale
      volumes:
      - name: tailscale-state
        emptyDir: {}
