name: build-observer-api
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - observer-api/**
      - .github/workflows/build-observer-api.yml

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/build-push-action@v6
        with:
          # adjust these two lines ONLY if your Dockerfile lives elsewhere
          context: ./observer-api
          # file: ./observer-api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/observer-api:latest
            ghcr.io/${{ secrets.GHCR_USERNAME }}/observer-api:${{ github.sha }}
