name: build-kubectl-runner
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - kubectl-runner/**
      - .github/workflows/build-kubectl-runner.yml
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/build-push-action@v6
        with:
          context: ./kubectl-runner
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/kubectl-runner:1.30.4
            ghcr.io/${{ secrets.GHCR_USERNAME }}/kubectl-runner:${{ github.sha }}
