name: build-omega
on:
  push:
    branches: [ main ]
    paths:
      - 'apps/arcs/omega-monitor/**'
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: ./apps/arcs/omega-monitor
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/omega-monitor:0.2.0
            ghcr.io/${{ github.actor }}/omega-monitor:latest
