name: build-sage-log-viewer
on:
  push:
    branches: [ main ]
    paths:
      - 'apps/arcs/sage-log-viewer/**'
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR (user namespace)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: ./apps/arcs/sage-log-viewer
          push: true
          tags: |
            ghcr.io/silentsage432/sage-log-viewer:0.1.0
            ghcr.io/silentsage432/sage-log-viewer:latest
